import React, { useState, useEffect } from 'react';
import { 
  BookOpen, 
  ShieldCheck, 
  CheckCircle2, 
  FileText, 
  Building2, 
  Sparkles, 
  ArrowRight,
  Database
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { getSources } from '../services/api';
import SourceModal from '../components/SourceModal';

export default function Sources() {
  const [sources, setSources] = useState([]);
  const [activeModalSource, setActiveModalSource] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    getSources().then(setSources);
  }, []);

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10">
      {/* Header */}
      <div className="space-y-2 text-center max-w-2xl mx-auto">
        <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-teal-50 text-teal-800 text-xs font-semibold border border-teal-200">
          <Database className="w-3.5 h-3.5 text-teal-600" />
          <span>Transparent RAG Knowledge Index</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-navy-900 tracking-tight">
          Knowledge Sources
        </h1>
        <p className="text-slate-500 text-sm">
          CivicAssist answers are grounded in structured municipal information.
        </p>
      </div>

      {/* Grounding Explanation Banner */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-2xs flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="flex items-start space-x-3.5">
          <div className="w-10 h-10 rounded-xl bg-civic-50 text-civic-700 flex items-center justify-center shrink-0">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-bold text-sm text-navy-900">Deterministic Municipal Grounding</h3>
            <p className="text-xs text-slate-500 leading-relaxed max-w-2xl mt-0.5">
              Every conversational response generated by Gemini in CivicAssist references one or more indexed municipal rulebooks below. Unverifiable questions safely trigger our transparent fallback mechanism rather than hallucinating.
            </p>
          </div>
        </div>
      </div>

      {/* Sources Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {sources.map((source) => (
          <div
            key={source.id}
            className="civic-card p-6 flex flex-col justify-between group space-y-4"
          >
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-bold uppercase tracking-wider text-civic-700 bg-civic-50 px-2 py-0.5 rounded border border-civic-200">
                  {source.category}
                </span>
                <span className="inline-flex items-center text-[10px] font-semibold text-teal-700">
                  <CheckCircle2 className="w-3 h-3 mr-1 text-teal-600" />
                  {source.status}
                </span>
              </div>

              <h3 className="text-base font-bold text-navy-900 group-hover:text-civic-700 transition-colors leading-tight">
                {source.title}
              </h3>

              <p className="text-xs text-slate-600 leading-relaxed line-clamp-3">
                {source.summary}
              </p>

              <div className="space-y-1.5 pt-2 border-t border-slate-100 text-[11px] text-slate-500">
                <p><strong>Authority: </strong>{source.authority}</p>
                <p><strong>Format: </strong>{source.format}</p>
              </div>

              {source.topics && (
                <div className="space-y-1 pt-1">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
                    Indexed Topics:
                  </span>
                  <div className="flex flex-wrap gap-1">
                    {source.topics.slice(0, 3).map((t, i) => (
                      <span key={i} className="text-[10px] bg-slate-100 text-slate-600 px-2 py-0.5 rounded">
                        {t}
                      </span>
                    ))}
                    {source.topics.length > 3 && (
                      <span className="text-[10px] text-slate-400">+{source.topics.length - 3} more</span>
                    )}
                  </div>
                </div>
              )}
            </div>

            <div className="pt-4 border-t border-slate-100 flex items-center justify-between">
              <button
                onClick={() => setActiveModalSource(source)}
                className="text-xs font-semibold text-civic-700 hover:text-civic-800 underline decoration-civic-300"
              >
                Inspect Excerpts
              </button>
              <button
                onClick={() => navigate(`/chat?q=${encodeURIComponent(`What information is available in ${source.title}?`)}`)}
                className="inline-flex items-center space-x-1 text-xs font-semibold text-slate-700 hover:text-navy-900"
              >
                <span>Query Source</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        ))}
      </div>

      <SourceModal
        source={activeModalSource}
        isOpen={Boolean(activeModalSource)}
        onClose={() => setActiveModalSource(null)}
      />
    </div>
  );
}
